### ISSUE TITLE
Unprivileged User Profile Prompt

### ISSUE THREAD

**Issue by breams** [omgmog/install-all-firefox#53]
It took a while for me to work out that it was a bug as I thought it was just something I'd messed up initially, but now that I've looked closer I can see that when an unprivileged user installs into `/Applications/Firefoxes/` none of the profiles work. Obviously, as a non-admin user you would have to have it installed either using `sudo` or another user account, but from what I can tell, when you run one of the apps you don't have permission to write to the profile in that path, or something like that.

So when I installed it on a machine where I had admin privileges in my user account it worked without any issue, and when I installed it in a path under my user directory (`~/Applications/Firefoxes/`) it also no longer prompted me for a profile on each launch.

I'm thinking that if the default install location is privileged then we should be storing profiles in a user writeable area rather than in the app package? Perahps `~/.firefox-profiles/` or something similar if you don't want to pollute `~/Library/`?

**Comment by omgmog** [comment]
This is sort of resolved in that you can do:

```
$ ./firefoxes.sh "all" "en-GB" "no_prompt" "/Users/myhomedir/Applications/"
```
