### ISSUE TITLE
Downloading Nightly is failing

### ISSUE THREAD

**Issue by kumar303** [omgmog/install-all-firefox#56]
I cloned the latest repo to install ``firefoxes.sh`` on a new machine and it looks like the Nightly download is failing. This seems to be the relevant output:

````
Downloading  firefox-40.0a1.en-US.mac.dmg

curl: (78) RETR response: 550

✖ Failed to download  firefox-40.0a1.en-US.mac.dmg!
````

I tried ``firefoxes.sh beta`` and it worked fine.

**Comment by omgmog** [comment]
Could be that they were uploading the latest nightly at the time that you tried?

You could manually download [the dmg](http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-trunk/firefox-40.0a1.en-US.mac.dmg) to the tmp directory and then try to install it.

I'm afraid as I don't use the beta/aurora/nightly builds, I'm not vested in supporting that part of the script.

**Comment by kumar303** [comment]
Here's a patch that fixed it for me: https://github.com/omgmog/install-all-firefox/pull/57
